### ISSUE TITLE
Multi packets not working - late packets

### ISSUE THREAD

**Issue by slavendam** [helium/router#343]
Hi,
there is problem with getting just one hotspot in Integration message all the time.
What I need is to get all hotspots when I do mapping and testing.

This is really important feature, because lot of people try to do mapping and testing, and they can do that just for 1 random hotspot, not with all.

When can we expect to get this fixed?

Thanks :)

**Comment by macpie** [comment]
Did you turn or the multi packets feature? By default it will only purchase 1 copy of the packet.

If you did, do you see a lot of late packets? (they are filtered out by default you will need to check Show Dropped Uplinks:Late)

**Comment by slavendam** [comment]
Yes, multi packet for one device set to 4 packets, and on another is set to All packets - no difference.
I can see them in Debug mode, and also when check "Show Dropped Uplinks: Late".
This is really important feature!


![image](https://user-images.githubusercontent.com/19354024/122638575-1f8f9300-d0f5-11eb-9ce7-375d20117928.png)

**Comment by jdgemm** [comment]
Have you confirmed there's other Hotspots in the area to provide additional packets?

**Comment by illperipherals** [comment]
I can confirm this.

**Comment by slavendam** [comment]
> Have you confirmed there's other Hotspots in the area to provide additional packets?

Yes, there are many hotspots. Same issue have few people from USA and UK.

**Comment by macpie** [comment]
Issue confirmed will be looking into it

**Comment by macpie** [comment]
This was addressed in https://github.com/helium/blockchain-core/pull/908

**Comment by slavendam** [comment]
This issue is still there. 
It is better then before, but still there.  As you can see, we can get 2-3 hotspots sometimes, but there are bunch of these which are dropped.
Same situation in EU and in US. @macpie 

![image](https://user-images.githubusercontent.com/19354024/129923277-1b735387-356e-4be4-be1e-f83f108edf03.png)

**Comment by macpie** [comment]
@slavendam this is being worked on in here https://github.com/helium/router/issues/396
